version: '2'

services:
  zeppelin:
    image: apache/zeppelin:0.10.0
    volumes:
      - ./logs:/logs
      - ./notebook:/notebook
    ports:
      - "8889:8080"
    environment:
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
  jupyter-lab:
    image: beakerx/beakerx
    container_name: jupyter-lab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
